# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - identifier: "writing"
    name: Communication
    url: ''
    weight: 10
  - name: "Writing Services"
    url: "/writing_services/"
    parent: "writing"
    weight: 20
  - name: "SciComm Webinars"
    url: "/webinars/"
    parent: "writing"
    weight: 35
  - name: "Science Writing Labs"
    url: "/better_writing/"
    parent: "writing"
    weight: 50
  - name: "Writing & Editing Tips"
    url: "/post/"
    parent: "writing"
    weight: 60
  - name: "Communication Resources"
    url: "/writing_resources/"
    parent: "writing"
    weight: 65
    
  - identifier: "DEI"
    name: Equity & Inclusion
    url: 'inclusion'
    weight: 80
  - name: "Services"
    url: "/inclusion/"
    parent: "DEI"
    weight: 90
  - name: "Webinars"
    url: "/inclusion_webinars/"
    parent: "DEI"
    weight: 100
  - name: "Resources"
    url: "/inclusion_resources/"
    parent: "DEI"
    weight: 110
    
  - name: Contact
    url: '#contact'
    weight: 120
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
