# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - identifier: "home"
    name: Home
    url: ''
    weight: 5
  - name: "About Dr. Hagan"
    url: "#about"
    parent: "home"
    weight: 10
  - name: "About ASCC"
    url: "#demo"
    parent: "home"
    weight: 15
  - name: "Available Services"
    url: "#services"
    parent: "home"
    weight: 20
  - name: "Writing/Editing Tips"
    url: "#posts"
    parent: "home"
    weight: 25
  - name: "ASCC Projects"
    url: "#projects"
    parent: "home"
    weight: 30
  - name: "Explore Tags"
    url: "#tags"
    parent: "home"
    weight: 35
  - name: "Contact"
    url: "#contact"
    parent: "home"
    weight: 40

  - identifier: "services"
    name: Services
    url: ''
    weight: 50
  - name: "Science Writing Labs"
    url: "/science-writing-labs/"
    parent: "services"
    weight: 55
  - name: "Writing & Editing"
    url: "/writing_services/"
    parent: "services"
    weight: 60
  - name: "SciComm Webinars"
    url: "/webinars/"
    parent: "services"
    weight: 65
  - name: "DEI Consulting"
    url: "/inclusion/"
    parent: "services"
    weight: 70
  - name: "DEI Webinars"
    url: "/inclusion_webinars/"
    parent: "services"
    weight: 75
    
  - identifier: "resources"
    name: Resources
    url: ''
    weight: 80
  - name: "Neutral Language Thesaurus"
    url: "/neutral-language-thesaurus/"
    parent: "resources"
    weight: 85
  - name: "Writing & Editing Tips"
    url: "/post/"
    parent: "resources"
    weight: 90
  - name: "Communication Resources"
    url: "/writing_resources/"
    parent: "resources"
    weight: 95
  - name: "DEI Resources"
    url: "/inclusion_resources/"
    parent: "resources"
    weight: 100
    
  - name: Contact
    url: '#contact'
    weight: 120
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
