# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: ASCC_theme
  theme_night: ASCC_theme
  font: ASCC_font_set
  font_size: L

# SEO

marketing:
  seo:
    site_type: LocalBusiness
    local_business_type: 'ProfessionalService'
    org_name: ''
    description: 'Alliance SciComm & Consulting’s vision is to Make Science Accessible. Both as a concept and a career. We providing consulting services that make academic communication and environments more accessible to all audiences including writing and editing services, communication professional development, and data analysis to identify and address institutional barriers in STEM.'
    twitter: 'Alliance_SCC'
  analytics:
    google_analytics: 'G-ZXE3JQEDSY'
    baidu_tongji: ''
  verification:
    google: 'tSj_8G0zjq093_cdn0ylR5Mpd_c69fuP_ghT8_NEqBE'
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: ' &copy; {year} Alliance SciComm & Consulting, LLC. Licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: ''
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: master
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true
